readme: change versioning
C2Devel/aws-sdk-go pull request #18
Opened 2024-02-07 13:11 UTC by vamping111

For changes to files under the `/model/` folder, and manual edits to autogenerated code (e.g. `/service/s3/api.go`) please create an Issue instead of a PR for those type of changes.

If there is an existing bug or feature this PR is answers please reference it here.

2024-02-08 15:47 UTC, PixarV requested changes

2024-02-08 15:47 UTC, PixarV commented on docs/c2/README.md
> +Схема версионирования: Версия должна соответствовать текущей версии облака C2.
Проговаривали, что не будет согласованности между версией провайдера или sdk и версией c2.
Лучше опиши коротко схему и первую версию года + `Версия` с маленькой буквы.

Такое же замечание для провайдера.

2024-02-08 15:47 UTC, PixarV commented on docs/c2/README.md
> +Является форком [aws-sdk-go](https://github.com/aws/aws-sdk-go) версии 1.44.10.
Чтобы было удобнее обновлять версию можно как-то унифицировать формат здесь и в провайдере. Например, в виде таблички Name Version.

2024-02-09 08:11 UTC, vamping111 commented on docs/c2/README.md
> +Схема версионирования: Версия должна соответствовать текущей версии облака C2.
Поправил

2024-02-09 08:11 UTC, vamping111 commented on docs/c2/README.md
> +Является форком [aws-sdk-go](https://github.com/aws/aws-sdk-go) версии 1.44.10.
Поправил

2024-02-09 09:51 UTC, PixarV requested changes

2024-02-09 09:51 UTC, PixarV commented on docs/c2/README.md
> +где X - последние две цифры текущего года(например, если сейчас 2024 год, то нужно написать 24), Y - мажорная версия(начинается с 0 и увеличиваясь, в том случае, когда внесенные изменения отменяют об
1. Не хватает пробелов перед `(`
2. Может это в список переформатировать: 
```
Схема версионирования: версия в формате X.Y.Z, где:
- X - <пояснение>
- Y - <пояснение> 
- Z - <пояснение>
```
3. Y: увеличиваясь -> увеличивается
4. Z: сейчас выглядит так, как будто минорная версия сохраняет значение при увеличении мажорной

Такое же замечание для провайдера.

2024-02-09 09:51 UTC, PixarV commented on docs/c2/README.md
> +Первая версия в каждом году должна быть в формате YY.0.0 .
1. Лишний пробел перед `.`
2. Формально у тебя для Y выше другое пояснение. Корректнее наверное написать `X.0.0`

Такое же замечание для провайдера.

2024-02-09 09:51 UTC, PixarV commented on docs/c2/README.md
> +Является форком [aws-sdk-go](https://github.com/aws/aws-sdk-go).
Думаю, это предложение можно убрать. Можно в табличке колонки назвать `Upstream name`, `Upstream version`

Такое же замечание для провайдера.

2024-02-09 09:51 UTC, PixarV commented on docs/c2/README.md
> +| [aws-sdk-go](https://github.com/aws/aws-sdk-go) | 1.44.10 |
Может добавить ссылку на тег для версии

Такое же замечание для провайдера.

2024-02-09 13:03 UTC, vamping111 commented on docs/c2/README.md
> +Первая версия в каждом году должна быть в формате YY.0.0 .
1) Специально поставил пробел перед ```.```, чтобы исключить вероятность того, что кто-то может проставить версию v24.1.1.(см точку в конце)

2024-02-09 13:21 UTC, vamping111 commented on docs/c2/README.md
> +где X - последние две цифры текущего года(например, если сейчас 2024 год, то нужно написать 24), Y - мажорная версия(начинается с 0 и увеличиваясь, в том случае, когда внесенные изменения отменяют об
Поправил

2024-02-09 13:21 UTC, vamping111 commented on docs/c2/README.md
> +Первая версия в каждом году должна быть в формате YY.0.0 .
2) Поправил

2024-02-09 13:21 UTC, vamping111 commented on docs/c2/README.md
> +Является форком [aws-sdk-go](https://github.com/aws/aws-sdk-go).
Поправил

2024-02-09 13:21 UTC, vamping111 commented on docs/c2/README.md
> +| [aws-sdk-go](https://github.com/aws/aws-sdk-go) | 1.44.10 |
Поправил

2024-02-09 14:37 UTC, PixarV commented on docs/c2/README.md
> +Стартовая версия: v24.0.0 .
```suggestion
Стартовая версия: **v24.0.0**.
```

2024-02-09 16:21 UTC, vamping111 commented on docs/c2/README.md
> +Стартовая версия: v24.0.0 .
Поправил

2024-02-12 14:01 UTC, PixarV approved these changes

2024-02-12 15:44 UTC, plushambush approved these changes

2024-02-29 09:40 UTC, merged