C2DEVEL-14695: return support of the backup service
C2Devel/aws-sdk-go pull request #34
Opened 2024-09-16 09:10 UTC by RudeZwloki7

2024-09-16 11:34 UTC, PixarV requested changes
Сделай пожалуйста коммитные сообщения чуть более подробными)

2024-09-16 11:34 UTC, PixarV commented on aws/corehandlers/handlers.go
> +	// if r.ClientInfo.SigningRegion == "" && aws.StringValue(r.Config.Region) == "" {
Не очень понятно зачем этот кусок кода закомментирован, а в истории коммитов и в задаче нет информаци про это изменение. Вынеси его в отдельный коммит пожалуйста и где-нибудь опиши

2024-09-16 11:34 UTC, PixarV commented on aws/corehandlers/handlers.go
> +	// } else if r.ClientInfo.Endpoint == "" {
Этот закомментированный кусок дублирует условие ниже, можно удалить

2024-09-16 11:34 UTC, PixarV commented on models/apis/backup/2018-11-15/api-2.json
> +          "documentation":"<p>The display name of a resource selection document.</p>"
Кажется тут ты только документацию добавляешь к полям. В этом репозитории документация к апи размещется в файлах `docs-2.json` и обновляется нами по желанию. Для этих полей документация там уже есть, так что кажется, что этот блок изменений можно откатить.

2024-09-16 11:34 UTC, PixarV commented on models/apis/backup/2018-11-15/api-2.json
> +        "Resources":{
В доке сказано, что это поле тоже обязательное

2024-09-16 11:34 UTC, PixarV commented on models/apis/backup/2018-11-15/api-2.json
> +        "CreatorRequestId":{"shape":"string"}
В доке нет этого поля

2024-09-23 06:54 UTC, RudeZwloki7 commented on aws/corehandlers/handlers.go
> +	// if r.ClientInfo.SigningRegion == "" && aws.StringValue(r.Config.Region) == "" {
В отдельный коммит вынес. Изначально убирал здесь проверку для возможности проставления пустого региона в конфиге провайдера.  В целом, если будем работать с пустыми регионами только на уровне arn в теле запроса, можно будет откатить эти изменения.

2024-09-23 06:55 UTC, RudeZwloki7 commented on aws/corehandlers/handlers.go
> +	// } else if r.ClientInfo.Endpoint == "" {
Убрал

2024-09-23 06:58 UTC, RudeZwloki7 commented on models/apis/backup/2018-11-15/api-2.json
> +          "documentation":"<p>The display name of a resource selection document.</p>"
Да, пропустил эту доку, когда приводил к схеме ботокора. Эту доку к полям полностью убрал, т.к. имеющаяся документация показалась более информативной

2024-09-23 07:00 UTC, RudeZwloki7 commented on models/apis/backup/2018-11-15/api-2.json
> +        "CreatorRequestId":{"shape":"string"}
Убрал

2024-09-23 07:02 UTC, RudeZwloki7 commented on models/apis/backup/2018-11-15/api-2.json
> +        "Resources":{
Добавил к обязательным полям

2024-10-04 09:15 UTC, PixarV commented on aws/corehandlers/handlers.go
> +	// if r.ClientInfo.SigningRegion == "" && aws.StringValue(r.Config.Region) == "" {
Пустой регион использовать не получается, тк есть датасорсы, которые используют значение региона как id, так что эту валидацию я бы все таки сохранила.

2024-10-04 09:34 UTC, PixarV requested changes
Оставила коммент + замечание про валидацию для региона еще осталось)

Переоформи еще пожалуйста немного описание ПРа. Мы забираем его прямо в changelog обычно, в качестве примера оформления можешь использовать #28

2024-10-04 09:34 UTC, PixarV commented on models/apis/backup/2018-11-15/api-2.json
> +        "ResourceArns"
Кажется тут должно быть `Resources`

2024-10-08 14:09 UTC, RudeZwloki7 commented on aws/corehandlers/handlers.go
> +	// if r.ClientInfo.SigningRegion == "" && aws.StringValue(r.Config.Region) == "" {
Вернул вариацию

2024-10-08 14:10 UTC, RudeZwloki7 commented on models/apis/backup/2018-11-15/api-2.json
> +        "ResourceArns"
Поправил

2024-10-11 12:38 UTC, PixarV approved these changes

2024-11-05 15:33 UTC, merged